config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :opinions
  resources :events
  devise_for :users
  resources :users, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "events#index"
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :event
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :set_opinion, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /opinions or /opinions.json
  def index
    @opinions = Opinion.all
  end

  # GET /opinions/1 or /opinions/1.json
  def show
  end

  # GET /opinions/new
  def new
    @opinion = Opinion.new
  end

  # GET /opinions/1/edit
  def edit
  end

  # POST /opinions or /opinions.json
  def create
    @opinion = Opinion.new(opinion_params)

    respond_to do |format|
      if @opinion.save
        format.html { redirect_to @opinion, notice: "Opinion was successfully created." }
        format.json { render :show, status: :created, location: @opinion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opinions/1 or /opinions/1.json
  def update
    respond_to do |format|
      if @opinion.update(opinion_params)
        format.html { redirect_to @opinion, notice: "Opinion was successfully updated." }
        format.json { render :show, status: :ok, location: @opinion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opinions/1 or /opinions/1.json
  def destroy
    @opinion.destroy
    respond_to do |format|
      format.html { redirect_to opinions_url, notice: "Opinion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opinion
      @opinion = Opinion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def opinion_params
      params.require(:opinion).permit(:title, :body, :starts, :event_id)
    end
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/opinions/_form.html.erb
<%= form_with(model: opinion) do |form| %>
  <% if opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
        <% opinion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :starts %>
    <%= form.number_field :starts %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/opinions/edit.html.erb
<h1>Editing Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

app/views/opinions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Opinions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Starts</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @opinions.each do |opinion| %>
      <tr>
        <td><%= opinion.title %></td>
        <td><%= opinion.body %></td>
        <td><%= opinion.starts %></td>
        <td><%= opinion.event_id %></td>
        <td><%= link_to 'Show', opinion %></td>
        <td><%= link_to 'Edit', edit_opinion_path(opinion) %></td>
        <td><%= link_to 'Destroy', opinion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Opinion', new_opinion_path %>

app/views/opinions/new.html.erb
<h1>New Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Back', opinions_path %>

app/views/opinions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @opinion.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @opinion.body %>
</p>

<p>
  <strong>Starts:</strong>
  <%= @opinion.starts %>
</p>

<p>
  <strong>Event:</strong>
  <%= @opinion.event_id %>
</p>

<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>